version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-node-server
    command: /usr/src/app/node_modules/.bin/nodemon server.js
    volumes:
      - ./server/:/usr/src/app
      # Bind mount only for app source code, not node_modules from host to avoid overwriting the container's node_modules
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: myapp-client
    container_name: myapp-react-client
    command: yarn start
    volumes:
      - ./client/:/usr/app
      # Same as server: avoid binding node_modules from host
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
